name: pemo_test_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  #For shared components
  pemo_test_component:
    path: packages/pemo_test_component/

  # Service locator
  get_it: ^8.0.3
  # Bloc for state management
  flutter_bloc: ^9.1.1
  # Value equality
  equatable: ^2.0.7
  # Dealing with forms inputs
  formz: ^0.8.0
  # For functional programming in dart
  dartz: ^0.10.1
  # Check internet access
  internet_connection_checker_plus: ^2.7.2
  # For http requests
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  # Local cache storage using NOSQL hive DB
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  hive_generator: ^2.0.1
  # For localization support
  easy_localization: ^3.0.7+1
  # For animations
  flutter_staggered_animations: ^1.1.1

  # For code generation
  freezed: ^2.5.7


dev_dependencies:
  flutter_test:
    sdk: flutter
#  mockito: ^5.4.6
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.4.0



flutter_gen:
  output: lib/core/generated/
  parse_metadata: true

flutter:
  uses-material-design: true
