name: pemo_test_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^8.0.3
  # Bloc for state management
  flutter_bloc: ^9.1.1
  # Value equality
  equatable: ^2.0.7
  # Dealing with forms inputs
  formz: ^0.8.0
  # Remote API
  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  # Local cache
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.6
  build_runner: ^2.5.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
