# The name of the package.
name: pemo_test_project
# A short description of the package.
description: "A new Flutter project."
# Prevents the package from being published to pub.dev.
publish_to: 'none'
# The version number of the package.
version: 1.0.0+1

# Specifies the Dart and Flutter SDK constraints for the package.
environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.0.5 <4.0.0"

# Lists the dependencies required by the package.
dependencies:
  flutter:
    sdk: flutter

  #For shared components
  # A local package for shared UI components and utilities.
  pemo_test_component:
    path: packages/pemo_test_component/

  # Service locator
  # A simple service locator for Dart and Flutter projects.
  get_it: ^8.0.3
  # Bloc for state management
  # A predictable state management library for Dart.
  flutter_bloc: ^9.1.1
  # Value equality
  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.7
  # Dealing with forms inputs
  # A form validation library for Dart & Flutter.
  formz: ^0.8.0
  # For functional programming in dart
  # Functional programming in Dart.
  dartz: ^0.10.1
  # Check internet access
  # A Flutter plugin to check for internet connection.
  internet_connection_checker_plus: ^2.7.2
  # For http requests
  # A powerful HTTP client for Dart, which supports Interceptors, Global configuration, FormData, Request Cancellation, File downloading, Timeout etc.
  dio: ^5.8.0+1
  # A Dio logger that prints request and response information.
  pretty_dio_logger: ^1.4.0
  # Local cache storage using NOSQL hive DB
  # A lightweight and fast key-value database written in pure Dart.
  hive: ^2.2.3
  # Flutter package for Hive.
  hive_flutter: ^1.1.0
  # A Flutter plugin for finding commonly used locations on the filesystem.
  path_provider: ^2.1.3
  # Generates TypeAdapters for Hive.
  hive_generator: ^2.0.1
  # For localization support
  # Easy and fast internationalization/localization for your Flutter apps.
  easy_localization: ^3.0.7+1
  # For animations
  # A Flutter package for adding staggered animations to your lists and grids.
  flutter_staggered_animations: ^1.1.1
  # For code generation
  # Code generation for immutable classes and unions.
  freezed: ^2.4.3
  # Annotations for the freezed code generator.
  freezed_annotation: ^2.4.1
  # Provides Dart Build System builders for handling JSON.
  json_annotation: ^4.9.0
  # For show animated bottom navigation bar
  # A Flutter package for creating animated bottom navigation bars.
  animated_bottom_navigation_bar: 1.4.0
  # For Shimmer effect
  # A Flutter package for adding a shimmer effect to your widgets.
  shimmer: ^3.0.0
  # For customize the splash screen
  # A Flutter package for customizing the native splash screen.
  flutter_native_splash: ^2.4.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  # Provides a build system for Dart.
  build_runner: ^2.5.4
  # Automatically generates code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.8.0
  # Linter rules for Dart and Flutter projects.
  flutter_lints: ^5.0.0
  # A Flutter code generator for your assets, fonts, colors, etc.
  flutter_gen_runner: ^5.4.0
  # A testing library for BLoC and Cubit.
  bloc_test: ^10.0.0
  # A mock library for Dart.
  mocktail: ^1.0.4
  # A command-line tool which simplifies the task of updating your Flutter app's launcher icon.
  flutter_launcher_icons: "^0.14.4"

# Configuration for flutter_launcher_icons.
flutter_launcher_icons:
  # Specifies the Android launcher icon name.
  android: "launcher_icon"
  # Whether to generate iOS icons.
  ios: true
  # The path to the image asset for the launcher icon.
  image_path: "assets/icons/app_icon.png"
  # The minimum Android SDK version.
  min_sdk_android: 21
  # Whether to remove the alpha channel from iOS icons.
  remove_alpha_ios: true

# Configuration for flutter_native_splash.
flutter_native_splash:
  # The background color of the splash screen.
  color: "#ffffff"
  # The image to display on the splash screen.
  image: assets/icons/app_icon.png

  # Android 12 specific splash screen configuration.
  android_12:
    # The image to display on the splash screen for Android 12.
    image: assets/icons/app_icon.png
    # The background color of the icon on the splash screen for Android 12.
    icon_background_color: "#ffffff"
  # Whether to generate a splash screen for the web.
  web: false


# Flutter specific configuration.
flutter:
  # Indicates that the project uses Material Design.
  uses-material-design: true
  # Specifies the assets to be included in the application.
  assets:
    - packages/pemo_test_component/assets/fonts/
    - assets/icons/

  # Defines the custom fonts used in the application.
  fonts:
    - family: FigtreeLight
      fonts:
        - asset: packages/pemo_test_component/assets/fonts/Figtree-Light.ttf
    - family: FigtreeRegular
      fonts:
        - asset: packages/pemo_test_component/assets/fonts/Figtree-Regular.ttf
    - family: FigtreeMedium
      fonts:
        - asset: packages/pemo_test_component/assets/fonts/Figtree-Medium.ttf

    - family: FigtreeSemiBold
      fonts:
        - asset: packages/pemo_test_component/assets/fonts/Figtree-SemiBold.ttf
    - family: FigtreeBold
      fonts:
        - asset: packages/pemo_test_component/assets/fonts/Figtree-Bold.ttf
