name: pemo_test_component
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  # For show svg files
  flutter_svg: ^2.2.0
  # For show and cache network source images
  cached_network_image: ^3.4.1
  # For show lottie animated files
  lottie: ^3.3.1
  # For Loading effect
  skeletonizer: ^1.4.3
  # For storybook
  storybook_flutter: ^0.14.1
  # For show long text content
  readmore: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.4.0

flutter_gen:
  output: generated/
  parse_metadata: true


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/svgs/
    - assets/fonts/

  fonts:
    - family: FigtreeLight
      fonts:
        - asset: assets/fonts/Figtree-Light.ttf

    - family: FigtreeRegular
      fonts:
        - asset: assets/fonts/Figtree-Regular.ttf


    - family: FigtreeMedium
      fonts:
        - asset: assets/fonts/Figtree-Medium.ttf

    - family: FigtreeSemiBold
      fonts:
        - asset: assets/fonts/Figtree-SemiBold.ttf

    - family: FigtreeBold
      fonts:
        - asset: assets/fonts/Figtree-Bold.ttf

